name: yalidine_form
description: Yalidine Form

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.12.2

  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  cloud_firestore: ^3.1.5
  flutter_riverpod: ^1.0.3
  cool_alert: ^1.1.0
  font_awesome_flutter: ^9.2.0
  qr_flutter: ^4.0.0

  # create pdf document
  pdf: ^3.1.0

  # save file
  path_provider: ^2.0.1

  # open pdf document
  open_file: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  ios : true
  android : true
  image_path: "assets/logo.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/logo_foreground.png"


flutter:

  uses-material-design: true

